### ISSUE TITLE
xtheadvector tuple create insert and extract

### ISSUE THREAD

**Issue by nihui** [ruyisdk/llvm-project#127]
How to create one `vfloat32m1x8_t` from eight `vfloat32m1_t` ?
How to extract one `vfloat32m1_t` by tuple index from one `vfloat32m1x8_t` ?

There is no `__riscv_vset_v_f32m1_f32m1x8` or `__riscv_vget_v_f32m1_f32m1x8` intrinsics as stated in https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/v0.12.x/auto-generated/intrinsic_funcs/11_miscellaneous_vector_functions.md#vector-insertion-functions

I have tried `v[0]` or `v.v0` but nothing magical happened

**Comment by imkiva** [comment]
The xtheadvector doesn't seem to have vget/vset on tuple types, as per https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1836682/1638774209491/Xuantie+900+Series+RVV-0.7.1+Intrinsic+Manual.pdf page 898.

Will emulate these intrinsics, thanks for reporting ❤️

**Comment by nihui** [comment]
some tests from gcc 15 on master branch
gcc provides all the following intrinsics with `-march=rv64gc_zfh_xtheadvector`

```
__riscv_vcreate_v_f32m1x8
__riscv_vset_v_f32m1_f32m1x8
__riscv_vget_v_f32m1x8_f32m1
```
