### ISSUE TITLE
Compilation of example?

### ISSUE THREAD

**Issue by joennlae** [ruyisdk/llvm-project#40]
Hello everyone :-)

Again, I want to say it is a fantastic project. I am eagerly following the progress :-)

I need some help compiling the example mentioned in the README.
I built the current head using the following:
```
cmake -DLLVM_TARGETS_TO_BUILD="RISCV" -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_BUILD_TYPE="RELEASE" -G Ninja ../llvm
```

And then I followed the step in the readme by using:

```
clang -march=rv64gc_xtheadvector memcpy_v.c -o memcpy_v
```

The error I encountered:
```
test.c:9:26: error: call to undeclared function '__riscv_th_vle8_v_u8m4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    9 |     vuint8m4_t vec_src = __riscv_th_vle8_v_u8m4(src, vl);
      |                          ^
test.c:9:16: error: initializing 'vuint8m4_t' (aka '__rvv_uint8m4_t') with an expression of incompatible type 'int'
    9 |     vuint8m4_t vec_src = __riscv_th_vle8_v_u8m4(src, vl);
      |                ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.c:10:5: error: call to undeclared function '__riscv_th_vse8_v_u8m4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   10 |     __riscv_th_vse8_v_u8m4(dst, vec_src, vl);
      |     ^
 ```

Can you explain to me what I am doing wrong?

Thank you :-)

**Comment by imkiva** [comment]
1. Can you show me the full path of the `clang` in your command? It should be the binary just built by `ninja`, in your case which should be `<pwd>/bin/clang`
2. And which commit are you working with now? I just tested the example in README with 5fab100ab3f4a01ff04e375d35cf1f81b5bfb1f6 and it works well.

**Comment by imkiva** [comment]
This is my debug configuration. Please replace `/home/kiva/tools/riscv/sysroot` with yours.

```
cmake -G Ninja \
-DCMAKE_C_COMPILER_LAUNCHER="ccache;distcc" \
-DCMAKE_CXX_COMPILER_LAUNCHER="ccache;distcc" \
-DLLVM_ENABLE_PROJECTS="clang" \
-DLLVM_TARGETS_TO_BUILD="RISCV" \
-DBUILD_SHARED_LIBS=true \
-DLLVM_USE_LINKER=mold \
-DDEFAULT_SYSROOT="/home/kiva/tools/riscv/sysroot" \
-DLLVM_DEFAULT_TARGET_TRIPLE="riscv64-unknown-linux-gnu"
```

**Comment by imkiva** [comment]
I reproduced the error by switching `CMAKE_BUILD_TYPE` from `Debug` to `Release`. 
I don't know why this affects intrinsic registration, and we are investigating now.

Please try switching to the debug build variant and see if the error persists.

**Comment by joennlae** [comment]
Thank you very much for the fast answer :-)

We will use DEBUG mode for the time being. Regarding the missing libraries, I had the same issue. I fix it like this:

```
export CXX="clang++ -march=rv64gc_xtheadvector -stdlib=libc++ -L/usr/lib/gcc/riscv64-redhat-linux/13/  -fuse-ld=lld -B /usr/lib/gcc/riscv64-redhat-linux/13/
```

Thank you again for the fast answer 💯

**Comment by imkiva** [comment]
Hi, @joennlae

Happy new year first! 
Can you check the current `xtheadvector` branch ([3cd92a0](https://github.com/ruyisdk/llvm-project/commit/3cd92a00a989554136c6774d36119a4b9b7aa98e)) with release builds? It should be fixed now.

**Comment by joennlae** [comment]
> Hi, @joennlae
> 
> Happy new year first! Can you check the current `xtheadvector` branch ([3cd92a0](https://github.com/ruyisdk/llvm-project/commit/3cd92a00a989554136c6774d36119a4b9b7aa98e)) with release builds? It should be fixed now.

Hi @imkiva 

Happy New Year to you, too :-)

I will test it in the upcoming days :-)

Thank you very much for fixing the issue :-)

**Comment by joennlae** [comment]
I tested it. It worked :-) Thank you :-)
